export const bonus_dummy = ([
  {
    key: 1,
    division: '벌점',
    score: -5,
    date: 20231113,
    lifSstArdCtnt: "숙제 안함",
  },
  {
    key: 2,
    division: '벌점',
    score: -5,
    date: 20231101,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 3,
    division: '상점',
    score: 1,
    date: 20230927,
    lifSstArdCtnt: "벌점 안받음",
  },
  {
    key: 4,
    division: '벌점',
    score: -5,
    date: 20230910,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 5,
    division: '상점',
    score: 1,
    date: 20230629,
    lifSstArdCtnt: "벌점 안받음",
  },
  {
    key: 6,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 7,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 8,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 9,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 10,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
  {
    key: 11,
    division: '벌점',
    score: -1,
    date: 20230530,
    lifSstArdCtnt: "외박함",
  },
 ]);